### ISSUE TITLE
Focal plane with more than one exposure

### ISSUE THREAD

**Issue by NiallMac** [esheldon/galsim_extra#10]
focal.yaml is not working when I provide an exposure list with more than one exposure. Appears to be some indexing error - the first image of the first exposure works ok, but then galsim seems to move onto the second image of the second exposure. @rmjarvis in case you need to run this to diagnose it, I can email you a tarball, it's about 40MB with the images though, so though best not to upload it to the repo. Anyway, here is the output:

`Using config file focal.yaml
Warning: config dict contains the following unexpected fields: ['bright_gal', 'faint_gal', 'nearby_gal', 'star'].
These fields are not (directly) processed by the config processing.
Start file 0 = output/sim_DECam_exp1_01.fits.fz
Start file 0 = output/sim_DECam_exp1_01.fits.fz
File 0 = output/sim_DECam_exp1_01.fits.fz: time = 5.245786 sec
Start file 1 = output/sim_DECam_exp2_02.fits.fz
File 1 = output/sim_DECam_exp2_02.fits.fz: time = 4.402212 sec
Done building files
File 0 = output/sim_DECam_exp1_01.fits.fz: time = 11.160861 sec
Start file 1 = output/sim_DECam_exp2_02.fits.fz
Start file 1 = output/sim_DECam_exp2_00.fits.fz
Exception caught for file 1 = output/sim_DECam_exp2_02.fits.fz
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/galsim/config/process.py", line 971, in MultiProcess
    result = job_func(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/galsim/config/output.py", line 222, in BuildFile
    data = builder.buildImages(output, config, file_num, image_num, obj_num, ignore, logger)
  File "/usr/local/lib/python2.7/site-packages/galsim/config/output.py", line 473, in buildImages
    image = galsim.config.BuildImage(base, image_num, obj_num, logger=logger)
  File "/usr/local/lib/python2.7/site-packages/galsim/config/image.py", line 224, in BuildImage
    SetupConfigImageSize(config, xsize, ysize, logger)
  File "/usr/local/lib/python2.7/site-packages/galsim/config/image.py", line 181, in SetupConfigImageSize
    wcs = galsim.config.BuildWCS(config['image'], 'wcs', config, logger)
  File "/usr/local/lib/python2.7/site-packages/galsim/config/wcs.py", line 89, in BuildWCS
    wcs = builder.buildWCS(param, base, logger)
  File "/usr/local/lib/python2.7/site-packages/galsim/config/wcs.py", line 174, in buildWCS
    return self.init_func(**kwargs)
  File "/usr/local/lib/python2.7/site-packages/galsim/fitswcs.py", line 1683, in FitsWCS
    text_file=text_file)
  File "/usr/local/lib/python2.7/site-packages/galsim/fits.py", line 1200, in __init__
    hdu_list, fin = _read_file(file_name, dir, file_compress)
  File "/usr/local/lib/python2.7/site-packages/galsim/fits.py", line 198, in __call__
    hdu_list = pyfits.open(file, 'readonly')
  File "/Users/maccrann.2/Library/Python/2.7/lib/python/site-packages/astropy/io/fits/hdu/hdulist.py", line 166, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/Users/maccrann.2/Library/Python/2.7/lib/python/site-packages/astropy/io/fits/hdu/hdulist.py", line 404, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/Users/maccrann.2/Library/Python/2.7/lib/python/site-packages/astropy/io/fits/hdu/hdulist.py", line 1015, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/Users/maccrann.2/Library/Python/2.7/lib/python/site-packages/astropy/utils/decorators.py", line 493, in wrapper
    return function(*args, **kwargs)
  File "/Users/maccrann.2/Library/Python/2.7/lib/python/site-packages/astropy/io/fits/file.py", line 144, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/Users/maccrann.2/Library/Python/2.7/lib/python/site-packages/astropy/io/fits/file.py", line 499, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/Users/maccrann.2/Library/Python/2.7/lib/python/site-packages/astropy/io/fits/util.py", line 393, in fileobj_open
    return open(filename, mode)
IOError: [Errno 2] No such file or directory: 'test_desdata/exp2/DECam_exp2_00.fits.fz'

File output/sim_DECam_exp2_02.fits.fz not written! Continuing on...
Start file 2 = output/sim_DECam_exp1_01.fits.fz
File 2 = output/sim_DECam_exp1_01.fits.fz: time = 4.482929 sec
Done building files
Exception caught for file 1 = output/sim_DECam_exp2_01.fits.fz
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/galsim/config/process.py", line 974, in MultiProcess
    done_func(logger, None, k, result, t2-t1)
  File "/usr/local/lib/python2.7/site-packages/galsim/config/output.py", line 119, in done_func
    raise RuntimeError("Files seem to be out of sync. %s != %s",file_name, file_name2)
RuntimeError: ('Files seem to be out of sync. %s != %s', 'output/sim_DECam_exp2_01.fits.fz', 'output/sim_DECam_exp2_02.fits.fz')

File output/sim_DECam_exp2_01.fits.fz not written! Continuing on...
Done building files
`

**Comment by rmjarvis** [comment]
I was thinking about this some more, and I think the "hack" we came up with this afternoon is actually the right solution.  It probably needs some more in-line comments to explain why it is correct, but when FocalPlane calls BuildFiles internally, it really is redefining what file_num means at that point.  And that is where the file_num should correspond to image_num.

So just changing file_num -> image_num in that line is probably sufficient.  Indeed I think the old definition of chip_num was fine with this change and is probably clearer than what we ended up with.

**Comment by NiallMac** [comment]
Thanks @rmjarvis , agreed that is sensible. I'll attempt to add some comments. This has got me wondering about the part of the code below, where we set the sequence of image random_seeds to repeat for all chips with the same file_num. 
:
```
        if not isinstance(rs,list):
            nobjects = galsim.config.GetCurrentValue('image.nobjects', base, int)
            first = galsim.config.ParseValue(base['image'], 'random_seed', base, int)[0]
            base['image']['random_seed'] = [
                {  # Used for most things.  Repeats for each chip.
                    'type' : 'Eval',
                    'str' : 'first_seed + obj_num % @image.nobjects',
                    'ifirst_seed' : '$%d + file_num * @image.nobjects'%first
                }
            ]
```
Will this use what FocalPlane considers to be the file_num, or what BuildFiles does? What if we want the same objects to repeat for all exposures? Can this just be achieved by setting 
```base['image']['random_seed'] = first```?

**Comment by rmjarvis** [comment]
I think you're right.  I think that should probably be exp_num, not file_num.  At least exp_num would be safe (since I believe this is only accessed after exp_num is set appropriately), whereas file_num might not be.

To repeat over all exposures, you'd want another item in the random_seed list (and then specify the corresponding `rng_num` to use it when you want that) with `'ifirst_seed' : first`.  i.e. not incrementing the first in the sequence with each new exposure.
